[project]
name = "levi"
version = "0.1.0"
description = "an cli application to compare the levenshtein distances between strings and files."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "pytest>=8.4.1",
]
